### PR TITLE
Replace Stack with Deque and remove redundant sort

### PR DESCRIPTION
**Pull request by bjornharrtell**
ref #274

### CODE REVIEW

**Comment by bjornharrtell** [comment]
@aaime that is indeed curious.

**Comment by bjornharrtell** [comment]
Ah.. the pop operation is expensive for ArrayDeque. I will change to LinkedList.

**Comment by aaime** [comment]
I see.. but also my fault. The tests I did earlier contained other improvements in the Geotools rendering subsystem that I did not include in this last test run.

Run it again with those improvements as well, and with the linked list: 32 seconds. Noice!

**Comment by bjornharrtell** [comment]
Sounds good enough for me to merge. :)

**Pull request merged**
