### PR TITLE
Optimize build write index performance

### PR DESCRIPTION
**Pull request by ChenyuWang98**
When the number of nodes is large, it takes longer and longer. The optimization effect is obvious. 
I think it can be merged into the master branch.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
I would not expect an iterator to be faster than indexing?

**Comment by ChenyuWang98** [comment]
image
The fact is that the effect is obvious

**Comment by michaelkirk** [comment]
This is likely because the test is using a LinkedList: https://github.com/flatgeobuf/flatgeobuf/blob/master/src/java/src/test/java/org/wololo/flatgeobuf/PackedRTreeTest.java#L27

**Comment by ChenyuWang98** [comment]
> 这可能是因为测试使用的是链表：[https ://github.com/flatgeobuf/flatgeobuf/blob/master/src/java/src/test/java/org/wololo/flatgeobuf/PackedRTreeTest.java#L27](https://github.com/flatgeobuf/flatgeobuf/blob/master/src/java/src/test/java/org/wololo/flatgeobuf/PackedRTreeTest.java#L27)


Yes, linked list is used

**Comment by bjornharrtell** [comment]
Hmm I see. I can merge it but would like to avoid star imports `import java.util.*` can you please change that @ChenyuWang98?

**Comment by ChenyuWang98** [comment]
> ` [db4b068](/flatgeobuf/flatgeobuf/pull/247/commits/db4b068a31cf169604afd0ddabe2fb919da46ca6)`


db4b068

**Comment by ChenyuWang98** [comment]
> Hmm I see. I can merge it but would like to avoid star imports `import java.util.*` can you please change that @ChenyuWang98?


db4b068

**Review by bjornharrtell — APPROVED** [review]

**Comment by bjornharrtell** [comment]
Thanks @ChenyuWang98

**Comment by ChenyuWang98** [comment]
I think a java version 3.24.2 should be released

**Pull request merged**
