### PR TITLE
Run Prettier Formatter and add it to CI

### PR DESCRIPTION
**Pull request by worace**
@bjornharrtell I was going to maybe commit this earlier so I don't have it as a confusing diff in https://github.com/flatgeobuf/flatgeobuf/pull/159

How do you feel about running this formatter step in CI? Is that going to be useful or annoying for people? Having it not formatted made it a little challenging for me since my editor kept trying to apply the prettier config on save, but it then of course made big diffs on the branch I was working on.

### CODE REVIEW

**Comment by worace** [comment]
Hm i guess there's not actually a CI on this? I don't see CircleCI reporting status on these PRs like I imagined

**Comment by bjornharrtell** [comment]
@worace yeah I seem to have a CI config that does not build PRs. I'll try to get that fixed ASAP.

I think it makes sense to verify the lint/formatting on CI.

**Comment by bjornharrtell** [comment]
I hope to have been able to enable CI to build PRs.

**Review by bjornharrtell — APPROVED** [review]
This looks fine so I will merge.

**Pull request merged**
