### PR TITLE
Fix HTTP 416 on some webservers

### PR DESCRIPTION
**Pull request by michaelkirk**
- [ts] NBD: clarify logging message
- [ts] NBD: use non-deprecated spelling
- [rust] Fix HTTP 416 on some webservers
- [ts] Fix HTTP 416 on some webservers

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Turns out it's rather difficult/involved to fully reproduce the situation that has been observed. Wanted to reproduce and try this fix there but as of yet unable to.

**Review by bjornharrtell — APPROVED** [review]
Done some testing that indicates this is looking good.

**Comment by michaelkirk** [comment]
You shouldbe able to reproduce it every time by fetching a bounding box that covers the last feature of the dataset.To figure that out, I did “select all” and logged the geometry of the last item (compare idx to the feature count from the header). On Dec 23, 2023, at 06:11, Björn Harrtell ***@***.***> wrote:﻿
Merged #339 into master.

**Comment by bjornharrtell** [comment]
Looks like it was reproduced by an empty bbox too :D - not sure that ever was intended to work at all though...

**Pull request merged**
