### PR TITLE
[js] add example serialize.js

### PR DESCRIPTION
**Pull request by 3-yuma-3**
Thank you for deesrialize.js, it's very helpful!!

Corresponding serialize.js will help developers more.

How about this change?

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Might be a helpful example but I think I need to make it more clear that the current ts/js impl. doesn't make spatial index

**Comment by 3-yuma-3** [comment]
How can I more clear it?
Should I add some comment in serialize.js to descrive it?

**Comment by bjornharrtell** [comment]
@3-yuma-3 I've added a comment, will merge. Thanks. :)

**Review by bjornharrtell — APPROVED** [review]

**Comment by 3-yuma-3** [comment]
@bjornharrtell   

Thanks a lot!!

**Pull request merged**
