### PR TITLE
Rust: Bump deps & 2021 edition, reexports, clippy

### PR DESCRIPTION
**Pull request by nyurik**
* Re-export the entire geozero because it has a number of other used traits like Error, so reexporting partial geozero creates more problem than solves
* Switch all crates to 2021 edition
* Cleanup crate.toml - we may want to switch to a proper workspace here
* bump all dependency versions to latest
* Address some clippy warnings

### CODE REVIEW

**Comment by nyurik** [comment]
cc: @pka

**Comment by bjornharrtell** [comment]
Thanks @nyurik, this looks good to me but if @pka is available I'll await his review before merge.

**Comment by pka** [comment]
All good for me, many great improvements!

**Comment by nyurik** [comment]
thx @pka and @bjornharrtell , feel free to merge/release.  I plan a release for geozero with some breaking changes, so this repo will have to be coordinated too :facepalm:

**Review by bjornharrtell — APPROVED** [review]
I note that this also upgrades flatbuffers to 23.5.26. I will see to it that this same version is used cross languages. It's not strictly required since the wire format is guaranteed to be compatible forever, but I still feel it's good to align this.

**Comment by bjornharrtell** [comment]
@nyurik do you agree this should be squash merged?

**Comment by nyurik** [comment]
Sure, I always squash merge

**Pull request merged**
