### PR TITLE
support for Z coordinates

### PR DESCRIPTION
**Pull request by xfischer**
Hi ! This is a draft PR for Z coordinates support.
For this to work, the NTS pull request should be merged first: https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/pull/76

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Looks promising but I'd prefer if you can avoid the whitespace changes.

**Comment by xfischer** [comment]
OK sorry about that, fixing.

**Comment by bjornharrtell** [comment]
Sorry to be a nitpick but can I also request to not change the placing of { ? :)

**Comment by xfischer** [comment]
Will do it from a fresh start

**Pull request closed without merging**
