### PR TITLE
Initial Go implementation of FlatGeoBuf.

### PR DESCRIPTION
**Pull request by bruno-ga**
- Includes a high-level API to create flatgeobuf files.
- Also a high-level API for reading those files (for now it only supports searching).
- Easily allows creating a flatgeobuf file for any source of geo-located data. All one need is a FeatureGenerator implementation.
- What is implemented seems to work but higher test coverage would be great.
- Data streaming is not implemented yet but can easily be done.

### CODE REVIEW

**Review by bjornharrtell — APPROVED** [review]
I'm a Go novice but LGTM! Nice work @bruno-ga!

**Comment by bjornharrtell** [comment]
I should try and add a go test run to CI before I merge this.

**Comment by bruno-ga** [comment]
> I'm a Go novice but LGTM! Nice work @bruno-ga!

Thanks. Also thanks to my employer (Openly) that allowed me to upstream all of these changes. This is actually production-hardened code so I am pretty sure it will be useful to other people.

**Comment by bjornharrtell** [comment]
It builds and test passes locally so I will merge and see if I can add CI later

**Comment by bruno-ga** [comment]
@bjornharrtell there was an oversight on my part and the module name still points to my internal repository. I went to fix it but it seems the code is not merged to master yet. Let me know when it is and I can sort things up.

**Comment by michaelkirk** [comment]
It looks like it's been merged into master with https://github.com/flatgeobuf/flatgeobuf/commit/bbc7116720f827ba968a2d741f3e6e24ff8071a5

Have you synced your local checkout with github? (`git pull`)

**Comment by bruno-ga** [comment]
> It looks like it's been merged into master with [bbc7116](https://github.com/flatgeobuf/flatgeobuf/commit/bbc7116720f827ba968a2d741f3e6e24ff8071a5)
> 
> Have you synced your local checkout with github? (`git pull`)

Ah, I am working on a fork so I need to update the fork. That is why it confused me. Thanks for the heads up.

I will prepare a new PR to fix the module path.

**Pull request merged**
